name: flutter_contact
version: 0.6.5+1
homepage: https://github.com/SunnyApp/flutter_contact
description: A Flutter plugin to retrieve, create and save contacts and contact-related events on Android and iOS devices.
maintainer: Eric Martineau
environment: 
  sdk: '>=2.6.0 <3.0.0'
  flutter: ^1.10.0
dependencies: 
  collection: ^1.14.11
  equatable: any
  intl: ^0.17.0
  logging: any
  logging_config: ^0.6.7+6
  quiver: ^2.1.3
  sunny_dart: any
  uuid: any
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  plugin: 
    platforms: 
      android: 
        package: co.sunnyapp.flutter_contact
        pluginClass: FlutterContactPlugin
      ios: 
        pluginClass: FlutterContactPlugin
